- hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Create web directory
      file:
        path: /var/www/contact-form
        state: directory

    - name: Deploy index.html
      copy:
        src: index.html
        dest: /var/www/contact-form/index.html

    - name: Print deployment message
      debug:
        msg: "index.html deployed successfully to /var/www/contact-form/"
